---
- name: Get usernames from /etc/passwd on all servers
  hosts: ubuntu_vms, pbs, hosts
  gather_facts: true
  ignore_errors: true
  tasks:
    - name: Print hostname
      debug:
        msg: "Hostname is {{ ansible_hostname }}"

    - name: Extract usernames
      shell: "cut -d: -f1 /etc/passwd"
      register: user_list

    - name: Store targeted hosts list on localhost
      set_fact:
        processed_hosts: "{{ ansible_play_hosts }}"
      delegate_to: localhost
      delegate_facts: true
      run_once: true

- name: Collect and save all usernames to one file
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Write all usernames to file
      copy:
        content: |
          {% for host in hostvars['localhost'].processed_hosts %}
          === {{ host }} ===
          {% if hostvars[host].user_list is defined and hostvars[host].user_list.stdout is defined %}
          {{ hostvars[host].user_list.stdout }}
          {% else %}
          (No user list available)
          {% endif %}
          {% endfor %}
        dest: /opt/ansible/users.txt
