- name: Update, upgrade, and reboot Ubuntu and Debian systems
  hosts: Ubuntu-VMs, Hosts, pbs
  gather_facts: true
  become: true
  ignore_unreachable: true
  tags: update,upgrade,reboot

  tasks:
    - name: Ensure only Debian/Ubuntu systems are targeted
      debug:
        msg: "Skipping non-Debian/Ubuntu host: {{ inventory_hostname }}"
      when: ansible_os_family != "Debian"
      changed_when: false
      run_once: true

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      tags: update

    - name: Upgrade all packages on servers (safe upgrade)
      apt:
        upgrade: safe
        force_apt_get: yes
      when: ansible_os_family == "Debian"
      tags: upgrade

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"
      tags: reboot

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: ansible_os_family == "Debian" and reboot_required_file.stat.exists
      tags: reboot

  handlers:
    # Example: Notify on reboot (optional)
    - name: Notify on reboot
      debug:
        msg: "{{ inventory_hostname }} has been rebooted"
      listen: reboot
