---
- name: Check for recent reboot and run Tailscale funnel if needed
  hosts: server1, server2
  become: yes
  become_user: root
  ignore_unreachable: true

  tasks:
    - name: Get the system's uptime in seconds
      shell: awk '{print $1}' /proc/uptime
      register: uptime_seconds

    - name: Start Tailscale funnel if reboot within the last 15 minutes
      shell: sudo tailscale funnel --bg 8096
      when: uptime_seconds.stdout | int < 900  # 900 seconds = 15 minutes

    - name: Report "nothing to do" if no recent reboot
      debug:
        msg: "Nothing to do!"
      when: uptime_seconds.stdout | int >= 900