---
- name: all ubuntu and debian update and upgrade with reboot on request
  hosts: Home-Net-VMs-Ubuntu-Debian-All, Home-Net-Hosts, Tailscale-Host-Ubuntu-Debian, Tailscale-VM-Ubuntu-Debian, Home-Net-pbs
  become: true
  become_user: root
  ignore_unreachable: true
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes